### PR TITLE
Added support for Kiss-Of-Death messages.

### PR DESCRIPTION
**Pull request by davidv1992**

### CODE REVIEW

**Comment by davidv1992** [comment]
Before I put in more work on this particular approach, I had the impression from the discussion on the mailing list back when I first suggested this that a different, more implicit approach was favored, in particular with regard to the RSTR, DENY and RATE codes.

Reflecting on that now I kind of see the appeal of that approach. Given that, do we still want to continue with the path from this PR?

**Comment by mlichvar** [comment]
I think we need something for the NTPv4 NTS NAK. It could be a new "authentication failed" flag instead of a KoD code if there is an agreement to not support the other codes.

**Comment by davidv1992** [comment]
Note: #12 is an alternative to this

**Comment by mlichvar** [comment]
Closing in favor of #12.

**Pull request closed without merging**
